#######################################################################
##################         CRUD  - USER      ###################
#######################################################################

### Retrieve All Users
GET http://localhost:8080/api/users

### Retrieve One User
GET http://localhost:8080/api/users/1

### Delete User
DELETE http://localhost:8080/api/users/4

### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Cersei"
}